eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    #port: ${PORT:7002}
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    

